dist: xenial
language: node_js
sudo: true
node_js:
  - "node"

services:
  - mongodb

branches:
  except:
    - /^v[0-9]/

if: tag IS blank

before_install:
  - sed -i -e "s/\"build\":\s[0-9]*/\"build\":"' '"$TRAVIS_BUILD_NUMBER/" component.json

install:
  - curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/microsoft.list
  - sudo apt-get update
  - sudo apt-get install -y powershell
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc

script: 
  - ./build.ps1
  - ./test.ps1
  - ./tag.ps1
  - ./release.ps1

after_script:
  - ./clean.ps1