// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/commandable.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorDescription struct {
	Category             string            `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Code                 string            `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	CorrelationId        string            `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Status               int32             `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Message              string            `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Cause                string            `protobuf:"bytes,6,opt,name=cause,proto3" json:"cause,omitempty"`
	StackTrace           string            `protobuf:"bytes,7,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	Details              map[string]string `protobuf:"bytes,8,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ErrorDescription) Reset()         { *m = ErrorDescription{} }
func (m *ErrorDescription) String() string { return proto.CompactTextString(m) }
func (*ErrorDescription) ProtoMessage()    {}
func (*ErrorDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_73bcf444ba5101f6, []int{0}
}

func (m *ErrorDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorDescription.Unmarshal(m, b)
}
func (m *ErrorDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorDescription.Marshal(b, m, deterministic)
}
func (m *ErrorDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorDescription.Merge(m, src)
}
func (m *ErrorDescription) XXX_Size() int {
	return xxx_messageInfo_ErrorDescription.Size(m)
}
func (m *ErrorDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorDescription.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorDescription proto.InternalMessageInfo

func (m *ErrorDescription) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ErrorDescription) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ErrorDescription) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *ErrorDescription) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ErrorDescription) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ErrorDescription) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

func (m *ErrorDescription) GetStackTrace() string {
	if m != nil {
		return m.StackTrace
	}
	return ""
}

func (m *ErrorDescription) GetDetails() map[string]string {
	if m != nil {
		return m.Details
	}
	return nil
}

// The request message containing the invocation request.
type InvokeRequest struct {
	Method               string   `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	CorrelationId        string   `protobuf:"bytes,2,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	ArgsEmpty            bool     `protobuf:"varint,3,opt,name=args_empty,json=argsEmpty,proto3" json:"args_empty,omitempty"`
	ArgsJson             string   `protobuf:"bytes,4,opt,name=args_json,json=argsJson,proto3" json:"args_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvokeRequest) Reset()         { *m = InvokeRequest{} }
func (m *InvokeRequest) String() string { return proto.CompactTextString(m) }
func (*InvokeRequest) ProtoMessage()    {}
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73bcf444ba5101f6, []int{1}
}

func (m *InvokeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeRequest.Unmarshal(m, b)
}
func (m *InvokeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeRequest.Marshal(b, m, deterministic)
}
func (m *InvokeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeRequest.Merge(m, src)
}
func (m *InvokeRequest) XXX_Size() int {
	return xxx_messageInfo_InvokeRequest.Size(m)
}
func (m *InvokeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeRequest proto.InternalMessageInfo

func (m *InvokeRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *InvokeRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *InvokeRequest) GetArgsEmpty() bool {
	if m != nil {
		return m.ArgsEmpty
	}
	return false
}

func (m *InvokeRequest) GetArgsJson() string {
	if m != nil {
		return m.ArgsJson
	}
	return ""
}

// The response message containing the invocation response
type InvokeReply struct {
	Error                *ErrorDescription `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ResultEmpty          bool              `protobuf:"varint,2,opt,name=result_empty,json=resultEmpty,proto3" json:"result_empty,omitempty"`
	ResultJson           string            `protobuf:"bytes,3,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *InvokeReply) Reset()         { *m = InvokeReply{} }
func (m *InvokeReply) String() string { return proto.CompactTextString(m) }
func (*InvokeReply) ProtoMessage()    {}
func (*InvokeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_73bcf444ba5101f6, []int{2}
}

func (m *InvokeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvokeReply.Unmarshal(m, b)
}
func (m *InvokeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvokeReply.Marshal(b, m, deterministic)
}
func (m *InvokeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvokeReply.Merge(m, src)
}
func (m *InvokeReply) XXX_Size() int {
	return xxx_messageInfo_InvokeReply.Size(m)
}
func (m *InvokeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InvokeReply.DiscardUnknown(m)
}

var xxx_messageInfo_InvokeReply proto.InternalMessageInfo

func (m *InvokeReply) GetError() *ErrorDescription {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *InvokeReply) GetResultEmpty() bool {
	if m != nil {
		return m.ResultEmpty
	}
	return false
}

func (m *InvokeReply) GetResultJson() string {
	if m != nil {
		return m.ResultJson
	}
	return ""
}

func init() {
	proto.RegisterType((*ErrorDescription)(nil), "commandable.ErrorDescription")
	proto.RegisterMapType((map[string]string)(nil), "commandable.ErrorDescription.DetailsEntry")
	proto.RegisterType((*InvokeRequest)(nil), "commandable.InvokeRequest")
	proto.RegisterType((*InvokeReply)(nil), "commandable.InvokeReply")
}

func init() { proto.RegisterFile("protos/commandable.proto", fileDescriptor_73bcf444ba5101f6) }

var fileDescriptor_73bcf444ba5101f6 = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xd1, 0x8a, 0xd3, 0x40,
	0x14, 0x86, 0x4d, 0xba, 0x6d, 0xd3, 0x93, 0x5d, 0x29, 0x83, 0xc8, 0x50, 0x29, 0x5b, 0x0b, 0x42,
	0x11, 0xac, 0xd0, 0xbd, 0x91, 0xbd, 0x92, 0x6d, 0xab, 0xac, 0x20, 0x96, 0xe0, 0x95, 0x37, 0x61,
	0x76, 0x72, 0xa8, 0xb1, 0x49, 0x26, 0xce, 0x4c, 0x0a, 0x79, 0x01, 0x2f, 0x7c, 0x0c, 0x9f, 0xc9,
	0x07, 0x92, 0x99, 0x49, 0x34, 0x2b, 0x65, 0xef, 0xe6, 0xff, 0xce, 0x39, 0x99, 0x7f, 0x7e, 0x4e,
	0x80, 0x96, 0x52, 0x68, 0xa1, 0x5e, 0x73, 0x91, 0xe7, 0xac, 0x48, 0xd8, 0x5d, 0x86, 0x4b, 0x8b,
	0x48, 0xd8, 0x41, 0xf3, 0xdf, 0x3e, 0x8c, 0xb7, 0x52, 0x0a, 0xb9, 0x41, 0xc5, 0x65, 0x5a, 0xea,
	0x54, 0x14, 0x64, 0x02, 0x01, 0x67, 0x1a, 0xf7, 0x42, 0xd6, 0xd4, 0x9b, 0x79, 0x8b, 0x51, 0xf4,
	0x57, 0x13, 0x02, 0x67, 0x5c, 0x24, 0x48, 0x7d, 0xcb, 0xed, 0x99, 0xbc, 0x80, 0xc7, 0x5c, 0x48,
	0x89, 0x19, 0x33, 0xe3, 0x71, 0x9a, 0xd0, 0x9e, 0xad, 0x5e, 0x74, 0xe8, 0x6d, 0x42, 0x9e, 0xc2,
	0x40, 0x69, 0xa6, 0x2b, 0x45, 0xcf, 0x66, 0xde, 0xa2, 0x1f, 0x35, 0x8a, 0x50, 0x18, 0xe6, 0xa8,
	0x14, 0xdb, 0x23, 0xed, 0xdb, 0xb9, 0x56, 0x92, 0x27, 0xd0, 0xe7, 0xac, 0x52, 0x48, 0x07, 0x96,
	0x3b, 0x41, 0x2e, 0x21, 0x54, 0x9a, 0xf1, 0x43, 0xac, 0x25, 0xe3, 0x48, 0x87, 0xb6, 0x06, 0x16,
	0x7d, 0x36, 0x84, 0x6c, 0x60, 0x98, 0xa0, 0x66, 0x69, 0xa6, 0x68, 0x30, 0xeb, 0x2d, 0xc2, 0xd5,
	0xcb, 0x65, 0x37, 0x86, 0xff, 0xdf, 0xbb, 0xdc, 0xb8, 0xe6, 0x6d, 0xa1, 0x65, 0x1d, 0xb5, 0xa3,
	0x93, 0x6b, 0x38, 0xef, 0x16, 0xc8, 0x18, 0x7a, 0x07, 0x6c, 0x03, 0x31, 0x47, 0x63, 0xef, 0xc8,
	0xb2, 0xaa, 0x0d, 0xc3, 0x89, 0x6b, 0xff, 0x8d, 0x37, 0xff, 0xe9, 0xc1, 0xc5, 0x6d, 0x71, 0x14,
	0x07, 0x8c, 0xf0, 0x7b, 0x85, 0x4a, 0x9b, 0xc7, 0xe7, 0xa8, 0xbf, 0x8a, 0xa4, 0xf9, 0x40, 0xa3,
	0x4e, 0x64, 0xe7, 0x9f, 0xca, 0x6e, 0x0a, 0xc0, 0xe4, 0x5e, 0xc5, 0x98, 0x97, 0xba, 0xb6, 0xf1,
	0x06, 0xd1, 0xc8, 0x90, 0xad, 0x01, 0xe4, 0x19, 0x58, 0x11, 0x7f, 0x53, 0xa2, 0xb0, 0xe9, 0x8e,
	0xa2, 0xc0, 0x80, 0x0f, 0x4a, 0x14, 0xf3, 0x1f, 0x1e, 0x84, 0xad, 0x99, 0x32, 0xab, 0xc9, 0x15,
	0xf4, 0xd1, 0x44, 0x60, 0x9d, 0x84, 0xab, 0xe9, 0x83, 0xe1, 0x44, 0xae, 0x97, 0x3c, 0x87, 0x73,
	0x89, 0xaa, 0xca, 0x74, 0x63, 0xc1, 0xb7, 0x16, 0x42, 0xc7, 0x9c, 0x89, 0x4b, 0x68, 0xa4, 0xb3,
	0xe1, 0x76, 0x00, 0x1c, 0x32, 0x46, 0x56, 0x9f, 0x20, 0x5c, 0xff, 0xbb, 0x8a, 0xbc, 0x85, 0x41,
	0x6a, 0x6d, 0x91, 0xc9, 0x3d, 0x0b, 0xf7, 0x82, 0x9b, 0xd0, 0x93, 0xb5, 0x32, 0xab, 0xe7, 0x8f,
	0x6e, 0xde, 0xc1, 0xb4, 0x4c, 0xcb, 0x57, 0x0a, 0xe5, 0x31, 0xe5, 0xa8, 0x96, 0x7b, 0x59, 0xf2,
	0x6e, 0xfb, 0xcd, 0xb8, 0x73, 0xdf, 0xce, 0x6c, 0xff, 0xce, 0xfb, 0x32, 0x70, 0x7f, 0xc6, 0x2f,
	0x3f, 0x78, 0x1f, 0xed, 0xd6, 0xf1, 0xfa, 0xe3, 0xe6, 0xce, 0xa1, 0xab, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x04, 0x47, 0x9d, 0xd4, 0x35, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommandableClient is the client API for Commandable service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommandableClient interface {
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeReply, error)
}

type commandableClient struct {
	cc *grpc.ClientConn
}

func NewCommandableClient(cc *grpc.ClientConn) CommandableClient {
	return &commandableClient{cc}
}

func (c *commandableClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeReply, error) {
	out := new(InvokeReply)
	err := c.cc.Invoke(ctx, "/commandable.Commandable/invoke", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandableServer is the server API for Commandable service.
type CommandableServer interface {
	Invoke(context.Context, *InvokeRequest) (*InvokeReply, error)
}

// UnimplementedCommandableServer can be embedded to have forward compatible implementations.
type UnimplementedCommandableServer struct {
}

func (*UnimplementedCommandableServer) Invoke(ctx context.Context, req *InvokeRequest) (*InvokeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invoke not implemented")
}

func RegisterCommandableServer(s *grpc.Server, srv CommandableServer) {
	s.RegisterService(&_Commandable_serviceDesc, srv)
}

func _Commandable_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandableServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/commandable.Commandable/Invoke",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandableServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Commandable_serviceDesc = grpc.ServiceDesc{
	ServiceName: "commandable.Commandable",
	HandlerType: (*CommandableServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "invoke",
			Handler:    _Commandable_Invoke_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/commandable.proto",
}
