version: '3.3'

services:

  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
      args:
        REPO: ${REPO}
    image: ${IMAGE:-pip/test}
    command: ${TEST_CMD:-go test ./test/...}
