// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test/protos/dummies.proto

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ErrorDescription struct {
	Category             string            `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Code                 string            `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	CorrelationId        string            `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Status               string            `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Message              string            `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Cause                string            `protobuf:"bytes,6,opt,name=cause,proto3" json:"cause,omitempty"`
	StackTrace           string            `protobuf:"bytes,7,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	Details              map[string]string `protobuf:"bytes,8,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ErrorDescription) Reset()         { *m = ErrorDescription{} }
func (m *ErrorDescription) String() string { return proto.CompactTextString(m) }
func (*ErrorDescription) ProtoMessage()    {}
func (*ErrorDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f5016849dbdfb81, []int{0}
}

func (m *ErrorDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrorDescription.Unmarshal(m, b)
}
func (m *ErrorDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrorDescription.Marshal(b, m, deterministic)
}
func (m *ErrorDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrorDescription.Merge(m, src)
}
func (m *ErrorDescription) XXX_Size() int {
	return xxx_messageInfo_ErrorDescription.Size(m)
}
func (m *ErrorDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrorDescription.DiscardUnknown(m)
}

var xxx_messageInfo_ErrorDescription proto.InternalMessageInfo

func (m *ErrorDescription) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ErrorDescription) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ErrorDescription) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *ErrorDescription) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ErrorDescription) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ErrorDescription) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

func (m *ErrorDescription) GetStackTrace() string {
	if m != nil {
		return m.StackTrace
	}
	return ""
}

func (m *ErrorDescription) GetDetails() map[string]string {
	if m != nil {
		return m.Details
	}
	return nil
}

type PagingParams struct {
	Skip                 int64    `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Take                 int32    `protobuf:"varint,2,opt,name=take,proto3" json:"take,omitempty"`
	Total                bool     `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PagingParams) Reset()         { *m = PagingParams{} }
func (m *PagingParams) String() string { return proto.CompactTextString(m) }
func (*PagingParams) ProtoMessage()    {}
func (*PagingParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f5016849dbdfb81, []int{1}
}

func (m *PagingParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PagingParams.Unmarshal(m, b)
}
func (m *PagingParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PagingParams.Marshal(b, m, deterministic)
}
func (m *PagingParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PagingParams.Merge(m, src)
}
func (m *PagingParams) XXX_Size() int {
	return xxx_messageInfo_PagingParams.Size(m)
}
func (m *PagingParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PagingParams.DiscardUnknown(m)
}

var xxx_messageInfo_PagingParams proto.InternalMessageInfo

func (m *PagingParams) GetSkip() int64 {
	if m != nil {
		return m.Skip
	}
	return 0
}

func (m *PagingParams) GetTake() int32 {
	if m != nil {
		return m.Take
	}
	return 0
}

func (m *PagingParams) GetTotal() bool {
	if m != nil {
		return m.Total
	}
	return false
}

type Dummy struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dummy) Reset()         { *m = Dummy{} }
func (m *Dummy) String() string { return proto.CompactTextString(m) }
func (*Dummy) ProtoMessage()    {}
func (*Dummy) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f5016849dbdfb81, []int{2}
}

func (m *Dummy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dummy.Unmarshal(m, b)
}
func (m *Dummy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dummy.Marshal(b, m, deterministic)
}
func (m *Dummy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dummy.Merge(m, src)
}
func (m *Dummy) XXX_Size() int {
	return xxx_messageInfo_Dummy.Size(m)
}
func (m *Dummy) XXX_DiscardUnknown() {
	xxx_messageInfo_Dummy.DiscardUnknown(m)
}

var xxx_messageInfo_Dummy proto.InternalMessageInfo

func (m *Dummy) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Dummy) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Dummy) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type DummiesPage struct {
	Total                int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*Dummy `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DummiesPage) Reset()         { *m = DummiesPage{} }
func (m *DummiesPage) String() string { return proto.CompactTextString(m) }
func (*DummiesPage) ProtoMessage()    {}
func (*DummiesPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f5016849dbdfb81, []int{3}
}

func (m *DummiesPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DummiesPage.Unmarshal(m, b)
}
func (m *DummiesPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DummiesPage.Marshal(b, m, deterministic)
}
func (m *DummiesPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DummiesPage.Merge(m, src)
}
func (m *DummiesPage) XXX_Size() int {
	return xxx_messageInfo_DummiesPage.Size(m)
}
func (m *DummiesPage) XXX_DiscardUnknown() {
	xxx_messageInfo_DummiesPage.DiscardUnknown(m)
}

var xxx_messageInfo_DummiesPage proto.InternalMessageInfo

func (m *DummiesPage) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *DummiesPage) GetData() []*Dummy {
	if m != nil {
		return m.Data
	}
	return nil
}

// The request message containing the page request.
type DummiesPageRequest struct {
	CorrelationId        string            `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Filter               map[string]string `protobuf:"bytes,2,rep,name=filter,proto3" json:"filter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Paging               *PagingParams     `protobuf:"bytes,3,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DummiesPageRequest) Reset()         { *m = DummiesPageRequest{} }
func (m *DummiesPageRequest) String() string { return proto.CompactTextString(m) }
func (*DummiesPageRequest) ProtoMessage()    {}
func (*DummiesPageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f5016849dbdfb81, []int{4}
}

func (m *DummiesPageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DummiesPageRequest.Unmarshal(m, b)
}
func (m *DummiesPageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DummiesPageRequest.Marshal(b, m, deterministic)
}
func (m *DummiesPageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DummiesPageRequest.Merge(m, src)
}
func (m *DummiesPageRequest) XXX_Size() int {
	return xxx_messageInfo_DummiesPageRequest.Size(m)
}
func (m *DummiesPageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DummiesPageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DummiesPageRequest proto.InternalMessageInfo

func (m *DummiesPageRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *DummiesPageRequest) GetFilter() map[string]string {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *DummiesPageRequest) GetPaging() *PagingParams {
	if m != nil {
		return m.Paging
	}
	return nil
}

// The request message containing the object id request.
type DummyIdRequest struct {
	CorrelationId        string   `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	DummyId              string   `protobuf:"bytes,2,opt,name=dummy_id,json=dummyId,proto3" json:"dummy_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DummyIdRequest) Reset()         { *m = DummyIdRequest{} }
func (m *DummyIdRequest) String() string { return proto.CompactTextString(m) }
func (*DummyIdRequest) ProtoMessage()    {}
func (*DummyIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f5016849dbdfb81, []int{5}
}

func (m *DummyIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DummyIdRequest.Unmarshal(m, b)
}
func (m *DummyIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DummyIdRequest.Marshal(b, m, deterministic)
}
func (m *DummyIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DummyIdRequest.Merge(m, src)
}
func (m *DummyIdRequest) XXX_Size() int {
	return xxx_messageInfo_DummyIdRequest.Size(m)
}
func (m *DummyIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DummyIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DummyIdRequest proto.InternalMessageInfo

func (m *DummyIdRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *DummyIdRequest) GetDummyId() string {
	if m != nil {
		return m.DummyId
	}
	return ""
}

// The request message containing the object value request.
type DummyObjectRequest struct {
	CorrelationId        string   `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	Dummy                *Dummy   `protobuf:"bytes,2,opt,name=dummy,proto3" json:"dummy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DummyObjectRequest) Reset()         { *m = DummyObjectRequest{} }
func (m *DummyObjectRequest) String() string { return proto.CompactTextString(m) }
func (*DummyObjectRequest) ProtoMessage()    {}
func (*DummyObjectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0f5016849dbdfb81, []int{6}
}

func (m *DummyObjectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DummyObjectRequest.Unmarshal(m, b)
}
func (m *DummyObjectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DummyObjectRequest.Marshal(b, m, deterministic)
}
func (m *DummyObjectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DummyObjectRequest.Merge(m, src)
}
func (m *DummyObjectRequest) XXX_Size() int {
	return xxx_messageInfo_DummyObjectRequest.Size(m)
}
func (m *DummyObjectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DummyObjectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DummyObjectRequest proto.InternalMessageInfo

func (m *DummyObjectRequest) GetCorrelationId() string {
	if m != nil {
		return m.CorrelationId
	}
	return ""
}

func (m *DummyObjectRequest) GetDummy() *Dummy {
	if m != nil {
		return m.Dummy
	}
	return nil
}

func init() {
	proto.RegisterType((*ErrorDescription)(nil), "dummies.ErrorDescription")
	proto.RegisterMapType((map[string]string)(nil), "dummies.ErrorDescription.DetailsEntry")
	proto.RegisterType((*PagingParams)(nil), "dummies.PagingParams")
	proto.RegisterType((*Dummy)(nil), "dummies.Dummy")
	proto.RegisterType((*DummiesPage)(nil), "dummies.DummiesPage")
	proto.RegisterType((*DummiesPageRequest)(nil), "dummies.DummiesPageRequest")
	proto.RegisterMapType((map[string]string)(nil), "dummies.DummiesPageRequest.FilterEntry")
	proto.RegisterType((*DummyIdRequest)(nil), "dummies.DummyIdRequest")
	proto.RegisterType((*DummyObjectRequest)(nil), "dummies.DummyObjectRequest")
}

func init() { proto.RegisterFile("test/protos/dummies.proto", fileDescriptor_0f5016849dbdfb81) }

var fileDescriptor_0f5016849dbdfb81 = []byte{
	// 599 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xad, 0x9d, 0x26, 0xce, 0x77, 0x9d, 0x2f, 0x54, 0xa3, 0x02, 0x6e, 0x58, 0x50, 0x59, 0xfc,
	0x74, 0xd3, 0x54, 0x2a, 0x1b, 0x5a, 0x81, 0x8a, 0x4a, 0x0a, 0x54, 0xaa, 0x44, 0x64, 0x21, 0x21,
	0xb1, 0x89, 0x26, 0x33, 0x17, 0x6b, 0x88, 0x1d, 0x9b, 0x99, 0x71, 0x25, 0xbf, 0x0e, 0x8f, 0xc3,
	0x8a, 0xa7, 0xe0, 0x39, 0x90, 0x67, 0xec, 0x90, 0x84, 0x08, 0x29, 0xec, 0xe6, 0xdc, 0x9f, 0x73,
	0xcf, 0x3d, 0x63, 0x0f, 0x1c, 0x68, 0x54, 0xfa, 0x24, 0x97, 0x99, 0xce, 0xd4, 0x09, 0x2f, 0xd2,
	0x54, 0xa0, 0x1a, 0x1a, 0x48, 0xbc, 0x1a, 0x86, 0x3f, 0x5c, 0xd8, 0xbb, 0x92, 0x32, 0x93, 0x23,
	0x54, 0x4c, 0x8a, 0x5c, 0x8b, 0x6c, 0x4e, 0x06, 0xd0, 0x65, 0x54, 0x63, 0x9c, 0xc9, 0x32, 0x70,
	0x0e, 0x9d, 0xa3, 0xff, 0xa2, 0x05, 0x26, 0x04, 0x76, 0x59, 0xc6, 0x31, 0x70, 0x4d, 0xdc, 0x9c,
	0xc9, 0x63, 0xe8, 0xb3, 0x4c, 0x4a, 0x4c, 0x68, 0xd5, 0x3e, 0x11, 0x3c, 0x68, 0x99, 0xec, 0xff,
	0x4b, 0xd1, 0x6b, 0x4e, 0xee, 0x41, 0x47, 0x69, 0xaa, 0x0b, 0x15, 0xec, 0x9a, 0x74, 0x8d, 0x48,
	0x00, 0x5e, 0x8a, 0x4a, 0xd1, 0x18, 0x83, 0xb6, 0x49, 0x34, 0x90, 0xec, 0x43, 0x9b, 0xd1, 0x42,
	0x61, 0xd0, 0x31, 0x71, 0x0b, 0xc8, 0x43, 0xf0, 0x95, 0xa6, 0x6c, 0x36, 0xd1, 0x92, 0x32, 0x0c,
	0x3c, 0x93, 0x03, 0x13, 0xfa, 0x50, 0x45, 0xc8, 0x2b, 0xf0, 0x38, 0x6a, 0x2a, 0x12, 0x15, 0x74,
	0x0f, 0x5b, 0x47, 0xfe, 0xe9, 0x93, 0x61, 0xb3, 0xfe, 0xfa, 0xae, 0xc3, 0x91, 0x2d, 0xbc, 0x9a,
	0x6b, 0x59, 0x46, 0x4d, 0xdb, 0xe0, 0x1c, 0x7a, 0xcb, 0x09, 0xb2, 0x07, 0xad, 0x19, 0x36, 0x66,
	0x54, 0xc7, 0x4a, 0xda, 0x2d, 0x4d, 0x8a, 0xc6, 0x08, 0x0b, 0xce, 0xdd, 0xe7, 0x4e, 0x78, 0x03,
	0xbd, 0x31, 0x8d, 0xc5, 0x3c, 0x1e, 0x53, 0x49, 0x53, 0x55, 0x39, 0xa6, 0x66, 0x22, 0x37, 0xcd,
	0xad, 0xc8, 0x9c, 0xab, 0x98, 0xa6, 0x33, 0xdb, 0xdc, 0x8e, 0xcc, 0xb9, 0x62, 0xd4, 0x99, 0xa6,
	0x89, 0x31, 0xaf, 0x1b, 0x59, 0x10, 0xbe, 0x86, 0xf6, 0xa8, 0x48, 0xd3, 0x92, 0xf4, 0xc1, 0x15,
	0xbc, 0x56, 0xe0, 0x0a, 0xde, 0x48, 0x72, 0x7f, 0x4b, 0x0a, 0xc0, 0x63, 0xd9, 0x5c, 0xe3, 0x5c,
	0xd7, 0xfe, 0x37, 0x30, 0x7c, 0x0b, 0xfe, 0xc8, 0x1a, 0x30, 0xae, 0x6d, 0xb5, 0x93, 0xac, 0x24,
	0x0b, 0x48, 0x08, 0xbb, 0x9c, 0x6a, 0x1a, 0xb8, 0xc6, 0xb2, 0xfe, 0xc2, 0x32, 0x33, 0x3e, 0x32,
	0xb9, 0xf0, 0xa7, 0x03, 0x64, 0x89, 0x29, 0xc2, 0xaf, 0x05, 0x2a, 0xbd, 0xe1, 0x03, 0x70, 0x36,
	0x7d, 0x00, 0x17, 0xd0, 0xf9, 0x2c, 0x12, 0x8d, 0xb2, 0x9e, 0xf1, 0x74, 0x65, 0xc6, 0x2a, 0xe7,
	0xf0, 0x8d, 0xa9, 0xb4, 0xf7, 0x52, 0xb7, 0x91, 0x63, 0xe8, 0xe4, 0xc6, 0x5a, 0xb3, 0xa0, 0x7f,
	0x7a, 0x77, 0x41, 0xb0, 0xec, 0x78, 0x54, 0x17, 0x0d, 0xce, 0xc0, 0x5f, 0x62, 0xd9, 0xea, 0x12,
	0x23, 0xe8, 0x9b, 0xbd, 0xaf, 0xf9, 0x96, 0x3b, 0x1e, 0x40, 0xb7, 0xd2, 0x54, 0x56, 0x05, 0x96,
	0xd5, 0xfc, 0x6b, 0xe5, 0x35, 0x0f, 0xa9, 0xf5, 0xae, 0x7c, 0x3f, 0xfd, 0x82, 0x4c, 0x6f, 0xc9,
	0xfb, 0x08, 0xda, 0x86, 0xc7, 0x90, 0xfe, 0x79, 0x3d, 0x36, 0x79, 0xfa, 0xdd, 0x05, 0xaf, 0xf6,
	0x92, 0x5c, 0x82, 0x1f, 0xa3, 0x9e, 0xd4, 0x75, 0xe4, 0xc1, 0x5f, 0xcc, 0x1e, 0xec, 0x6f, 0x4a,
	0x86, 0x3b, 0xe4, 0x05, 0xdc, 0x69, 0x38, 0xca, 0xc9, 0xb4, 0x5a, 0x8a, 0xdc, 0x5f, 0x9d, 0xbc,
	0x30, 0x68, 0xb0, 0x26, 0x29, 0xdc, 0x21, 0x2f, 0xa1, 0xc7, 0x24, 0x52, 0x8d, 0x96, 0x60, 0x4d,
	0xc2, 0xaa, 0x0f, 0x9b, 0xdb, 0x8b, 0x9c, 0xff, 0x73, 0xfb, 0x05, 0x10, 0x8e, 0x09, 0x36, 0xed,
	0x5b, 0xcb, 0xbf, 0x3c, 0x83, 0x83, 0x5c, 0xe4, 0xc7, 0x0a, 0xe5, 0xad, 0x60, 0xa8, 0x86, 0xb1,
	0xcc, 0x59, 0x53, 0x74, 0xd9, 0x6b, 0x8c, 0xaa, 0xde, 0xd3, 0xb1, 0xf3, 0xa9, 0x63, 0xdf, 0xd9,
	0x6f, 0x6e, 0xeb, 0xdd, 0xcd, 0xc7, 0xa9, 0x45, 0xcf, 0x7e, 0x05, 0x00, 0x00, 0xff, 0xff, 0x22,
	0x15, 0x9f, 0xc1, 0x83, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DummiesClient is the client API for Dummies service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DummiesClient interface {
	GetDummies(ctx context.Context, in *DummiesPageRequest, opts ...grpc.CallOption) (*DummiesPage, error)
	GetDummyById(ctx context.Context, in *DummyIdRequest, opts ...grpc.CallOption) (*Dummy, error)
	CreateDummy(ctx context.Context, in *DummyObjectRequest, opts ...grpc.CallOption) (*Dummy, error)
	UpdateDummy(ctx context.Context, in *DummyObjectRequest, opts ...grpc.CallOption) (*Dummy, error)
	DeleteDummyById(ctx context.Context, in *DummyIdRequest, opts ...grpc.CallOption) (*Dummy, error)
}

type dummiesClient struct {
	cc grpc.ClientConnInterface
}

func NewDummiesClient(cc grpc.ClientConnInterface) DummiesClient {
	return &dummiesClient{cc}
}

func (c *dummiesClient) GetDummies(ctx context.Context, in *DummiesPageRequest, opts ...grpc.CallOption) (*DummiesPage, error) {
	out := new(DummiesPage)
	err := c.cc.Invoke(ctx, "/dummies.Dummies/get_dummies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dummiesClient) GetDummyById(ctx context.Context, in *DummyIdRequest, opts ...grpc.CallOption) (*Dummy, error) {
	out := new(Dummy)
	err := c.cc.Invoke(ctx, "/dummies.Dummies/get_dummy_by_id", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dummiesClient) CreateDummy(ctx context.Context, in *DummyObjectRequest, opts ...grpc.CallOption) (*Dummy, error) {
	out := new(Dummy)
	err := c.cc.Invoke(ctx, "/dummies.Dummies/create_dummy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dummiesClient) UpdateDummy(ctx context.Context, in *DummyObjectRequest, opts ...grpc.CallOption) (*Dummy, error) {
	out := new(Dummy)
	err := c.cc.Invoke(ctx, "/dummies.Dummies/update_dummy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dummiesClient) DeleteDummyById(ctx context.Context, in *DummyIdRequest, opts ...grpc.CallOption) (*Dummy, error) {
	out := new(Dummy)
	err := c.cc.Invoke(ctx, "/dummies.Dummies/delete_dummy_by_id", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DummiesServer is the server API for Dummies service.
type DummiesServer interface {
	GetDummies(context.Context, *DummiesPageRequest) (*DummiesPage, error)
	GetDummyById(context.Context, *DummyIdRequest) (*Dummy, error)
	CreateDummy(context.Context, *DummyObjectRequest) (*Dummy, error)
	UpdateDummy(context.Context, *DummyObjectRequest) (*Dummy, error)
	DeleteDummyById(context.Context, *DummyIdRequest) (*Dummy, error)
}

// UnimplementedDummiesServer can be embedded to have forward compatible implementations.
type UnimplementedDummiesServer struct {
}

func (*UnimplementedDummiesServer) GetDummies(ctx context.Context, req *DummiesPageRequest) (*DummiesPage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDummies not implemented")
}
func (*UnimplementedDummiesServer) GetDummyById(ctx context.Context, req *DummyIdRequest) (*Dummy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDummyById not implemented")
}
func (*UnimplementedDummiesServer) CreateDummy(ctx context.Context, req *DummyObjectRequest) (*Dummy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDummy not implemented")
}
func (*UnimplementedDummiesServer) UpdateDummy(ctx context.Context, req *DummyObjectRequest) (*Dummy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDummy not implemented")
}
func (*UnimplementedDummiesServer) DeleteDummyById(ctx context.Context, req *DummyIdRequest) (*Dummy, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDummyById not implemented")
}

func RegisterDummiesServer(s *grpc.Server, srv DummiesServer) {
	s.RegisterService(&_Dummies_serviceDesc, srv)
}

func _Dummies_GetDummies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DummiesPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DummiesServer).GetDummies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dummies.Dummies/GetDummies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DummiesServer).GetDummies(ctx, req.(*DummiesPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dummies_GetDummyById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DummyIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DummiesServer).GetDummyById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dummies.Dummies/GetDummyById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DummiesServer).GetDummyById(ctx, req.(*DummyIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dummies_CreateDummy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DummyObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DummiesServer).CreateDummy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dummies.Dummies/CreateDummy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DummiesServer).CreateDummy(ctx, req.(*DummyObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dummies_UpdateDummy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DummyObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DummiesServer).UpdateDummy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dummies.Dummies/UpdateDummy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DummiesServer).UpdateDummy(ctx, req.(*DummyObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Dummies_DeleteDummyById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DummyIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DummiesServer).DeleteDummyById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dummies.Dummies/DeleteDummyById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DummiesServer).DeleteDummyById(ctx, req.(*DummyIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Dummies_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dummies.Dummies",
	HandlerType: (*DummiesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get_dummies",
			Handler:    _Dummies_GetDummies_Handler,
		},
		{
			MethodName: "get_dummy_by_id",
			Handler:    _Dummies_GetDummyById_Handler,
		},
		{
			MethodName: "create_dummy",
			Handler:    _Dummies_CreateDummy_Handler,
		},
		{
			MethodName: "update_dummy",
			Handler:    _Dummies_UpdateDummy_Handler,
		},
		{
			MethodName: "delete_dummy_by_id",
			Handler:    _Dummies_DeleteDummyById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test/protos/dummies.proto",
}
